import 'package:MedInvent/features/Map/categories.dart';
import 'package:MedInvent/features/Map/doctor.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

List<Doctor> doctors = [
  Doctor(
      name: "Albert Alexander",
      speciality: Categories.Physician,
      arriveTime: const TimeOfDay(hour: 17, minute: 30),
      leaveTime: const TimeOfDay(hour: 19, minute: 30),
      datesList: ['Monday', 'Wednesday', 'Saturday'],
      location: const LatLng(6.797554, 79.891743)),
  Doctor(
      name: "Stephen Strange",
      speciality: Categories.Cardiology,
      arriveTime: const TimeOfDay(hour: 17, minute: 30),
      leaveTime: const TimeOfDay(hour: 19, minute: 30),
      datesList: ['Monday', 'Wednesday', 'Saturday'],
      location: const LatLng(6.800708, 79.897652)),
  Doctor(
      name: "Stephen Strange",
      speciality: Categories.Cardiology,
      arriveTime: const TimeOfDay(hour: 17, minute: 30),
      leaveTime: const TimeOfDay(hour: 19, minute: 30),
      datesList: ['Monday', 'Wednesday', 'Saturday'],
      location: const LatLng(6.800708, 79.897652)),
  Doctor(
      name: "Kapila Gunarathne",
      speciality: Categories.Pediatric,
      arriveTime: const TimeOfDay(hour: 17, minute: 30),
      leaveTime: const TimeOfDay(hour: 19, minute: 30),
      datesList: ['Monday', 'Wednesday', 'Saturday'],
      location: const LatLng(6.793944, 79.907120)),
  Doctor(
    name: "Albert Alexander",
    speciality: Categories.Physician,
    arriveTime: const TimeOfDay(hour: 17, minute: 30),
    leaveTime: const TimeOfDay(hour: 19, minute: 30),
    datesList: ['Monday', 'Wednesday', 'Saturday'],
    location: const LatLng(6.797554, 79.891743),
  ),
  Doctor(
    name: "Bianca Baker",
    speciality: Categories.Urology,
    arriveTime: const TimeOfDay(hour: 14, minute: 30),
    leaveTime: const TimeOfDay(hour: 17, minute: 30),
    datesList: ['Tuesday', 'Thursday', 'Friday'],
    location: const LatLng(6.927079, 79.861244),
  ),
  Doctor(
    name: "Carlos Cruz",
    speciality: Categories.Gynecology,
    arriveTime: const TimeOfDay(hour: 14, minute: 30),
    leaveTime: const TimeOfDay(hour: 16, minute: 30),
    datesList: ['Monday', 'Wednesday', 'Saturday'],
    location: const LatLng(7.270720, 80.587790),
  ),
  Doctor(
    name: "Diana Davis",
    speciality: Categories.Dermatology,
    arriveTime: const TimeOfDay(hour: 14, minute: 30),
    leaveTime: const TimeOfDay(hour: 16, minute: 30),
    datesList: ['Monday', 'Tuesday', 'Thursday'],
    location: const LatLng(6.036703, 80.217035),
  ),
  Doctor(
    name: "Emily Evans",
    speciality: Categories.Physician,
    arriveTime: const TimeOfDay(hour: 14, minute: 30),
    leaveTime: const TimeOfDay(hour: 16, minute: 30),
    datesList: ['Tuesday', 'Thursday', 'Saturday'],
    location: const LatLng(7.873054, 80.771797),
  ),
  Doctor(
    name: "Frank Foster",
    speciality: Categories.Endocrinology,
    arriveTime: const TimeOfDay(hour: 14, minute: 30),
    leaveTime: const TimeOfDay(hour: 16, minute: 30),
    datesList: ['Monday', 'Wednesday', 'Friday'],
    location: const LatLng(6.717692, 81.104851),
  ),
  Doctor(
    name: "Grace Garcia",
    speciality: Categories.Cardiology,
    arriveTime: const TimeOfDay(hour: 14, minute: 30),
    leaveTime: const TimeOfDay(hour: 16, minute: 30),
    datesList: ['Tuesday', 'Thursday', 'Saturday'],
    location: const LatLng(6.705539, 80.384473),
  ),
  Doctor(
    name: "Henry Hernandez",
    speciality: Categories.Hematology,
    arriveTime: const TimeOfDay(hour: 14, minute: 30),
    leaveTime: const TimeOfDay(hour: 16, minute: 30),
    datesList: ['Monday', 'Wednesday', 'Friday'],
    location: const LatLng(8.572098, 81.220879),
  ),
  Doctor(
    name: "Isabel Ingram",
    speciality: Categories.Physician,
    arriveTime: const TimeOfDay(hour: 14, minute: 30),
    leaveTime: const TimeOfDay(hour: 16, minute: 30),
    datesList: ['Tuesday', 'Thursday', 'Saturday'],
    location: const LatLng(7.296004, 80.635847),
  ),
  Doctor(
    name: "Jack Johnson",
    speciality: Categories.Urology,
    arriveTime: const TimeOfDay(hour: 14, minute: 30),
    leaveTime: const TimeOfDay(hour: 16, minute: 30),
    datesList: ['Monday', 'Wednesday', 'Friday'],
    location: const LatLng(6.124228, 81.101034),
  ),
  Doctor(
    name: "Isabel Ingram",
    speciality: Categories.Physician,
    arriveTime: const TimeOfDay(hour: 14, minute: 30),
    leaveTime: const TimeOfDay(hour: 16, minute: 30),
    datesList: ['Tuesday', 'Thursday', 'Saturday'],
    location: const LatLng(6.805229, 79.977944),
  ),
  Doctor(
    name: "Jack Johnson",
    speciality: Categories.Urology,
    arriveTime: const TimeOfDay(hour: 14, minute: 30),
    leaveTime: const TimeOfDay(hour: 16, minute: 30),
    datesList: ['Monday', 'Wednesday', 'Friday'],
    location: const LatLng(6.811248, 79.975530),
  ),
];
